### ISSUE TITLE
Network error is "hidden" by catch(Exception)

### ISSUE THREAD

**Issue by lionkmp** [EVO-Payments/EVO_Gateway_.Net_SDK#10]
Hi,
In ApiCall.cs line 208, this part catches ALL type of exceptions and **replaces** them with an ActionCallException:

```
           catch (Exception ex)
            {
                Tools.WriteToLogFile(ex.ToString());
                var exception = new ActionCallException("A token error occurred");
                throw exception;
            }

```

After this, only TurnKey LOG contains the real error, but that's not something an API consumer generally examines to handle the error in details.

For example, this **network error** in HTTP POST remains undetected and appears to the application as "Token Error" due to the above catch.

```
System.Net.WebException: The remote name could not be resolved: 'api.evopaymentgateway.com'
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at Turnkey.ApiCall.<PostToApi>d__10.MoveNext() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 129
System.AggregateException: One or more errors occurred. ---> Turnkey.exception.PostToApiException: A communication error occurred
   at Turnkey.ApiCall.<PostToApi>d__10.MoveNext() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 136
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Turnkey.ApiCall.Execute() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 183
---> (Inner Exception #0) Turnkey.exception.PostToApiException: A communication error occurred
   at Turnkey.ApiCall.<PostToApi>d__10.MoveNext() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 136<---

System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 78.133.228.111:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at Turnkey.ApiCall.<PostToApi>d__10.MoveNext() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 129
System.AggregateException: One or more errors occurred. ---> Turnkey.exception.PostToApiException: A communication error occurred
   at Turnkey.ApiCall.<PostToApi>d__10.MoveNext() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 136
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Turnkey.ApiCall.Execute() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 183
---> (Inner Exception #0) Turnkey.exception.PostToApiException: A communication error occurred
   at Turnkey.ApiCall.<PostToApi>d__10.MoveNext() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 136<---

System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 78.133.228.111:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at Turnkey.ApiCall.<PostToApi>d__10.MoveNext() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 129
System.AggregateException: One or more errors occurred. ---> Turnkey.exception.PostToApiException: A communication error occurred
   at Turnkey.ApiCall.<PostToApi>d__10.MoveNext() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 136
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Turnkey.ApiCall.Execute() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 183
---> (Inner Exception #0) Turnkey.exception.PostToApiException: A communication error occurred
   at Turnkey.ApiCall.<PostToApi>d__10.MoveNext() in C:\Users\lion\Downloads\EVO_Gateway_.Net_SDK-master\TurnkeySourceCode\Turnkey\ApiCall.cs:line 136<---
```

Possible solutions could be, if you agree:

1.  do not catch this at all, so that API consumer can decide to catch "WebException" and handle
2.  include the original exception always as "inner" in the throw new Ex command (however that is more complicated to handle/catch) 

If you recommend handling this (network error) on some other way by API consumer, please let me know. But I think, in general catching ALL exception (with catch(Exception)) and replacing them to another exception class is not a good idea. This completely hides the original error from the caller.

ps: could you please add date/time to Log file entries, so that I can identify whether this is one error or multiple errors... :)

**Comment by lionkmp** [comment]
I forgot the most important thing. When a developers first face this:

`Turnkey.exception.ActionCallException: A token error occurred`

They will not know it's a **simple network connection error**. That's the main reason I find it important to not hide "WebException".  Originally I even reported Token Error to customer support and asked for help - totally unnecessarily. This is not a "token error" in my opinion. Thanks!
